[deploy]
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[environment.variables]
PORT = "8000"

[[services]]
name = "backend"
location = "apps/backend"
builder = "heroku/python"
buildCommand = "pip install -r requirements.txt"
startCommand = "python -m uvicorn main:app --host=0.0.0.0 --port=$PORT"

[[services.dns]]
domains = ["backend.up.railway.app"]
